import { StyleSheet } from 'react-native';
import { CellColors } from '../types';
import {
  amber,
  black,
  blue,
  blueGrey,
  brown,
  cyan,
  deepPurple,
  gray,
  green,
  indigo,
  lightAmber,
  lightBlack,
  lightBlue,
  lightBlueGrey,
  lightCyan,
  lightDeepPurple,
  lightGray,
  lightGreen,
  lightIndigo,
  lightPink,
  lightPurple,
  lightRed,
  lightTeal,
  pink,
  purple,
  red,
  teal,
  white,
  yellow,
} from './colors';
import {
  FLAT_LIST_MARGIN_SIZE,
  GAP_BETWEEN_COMPONENTS,
  SUDOKU_CELL_NORMAL_MARGIN,
  SUDOKU_CELL_SUBGRID_MARGIN,
} from './constants';

const cellColorTheme: Record<string, CellColors> = {
  amber: {
    primary: amber,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: amber,
    text: black,
    selectedBackground: amber,
    selectedOpacity: white,
    selectedText: brown,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightAmber,
    highlightText: black,
    remove: amber,
    reset: amber,
    reveal: red,
    showHints: yellow,
    barStyle: 'dark-content',
  },
  black: {
    primary: black,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: black,
    text: black,
    selectedBackground: black,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightBlack,
    highlightText: black,
    remove: black,
    reset: black,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  blue: {
    primary: blue,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: blue,
    text: black,
    selectedBackground: blue,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightBlue,
    highlightText: black,
    remove: blue,
    reset: blue,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  cyan: {
    primary: cyan,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: cyan,
    text: black,
    selectedBackground: cyan,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightCyan,
    highlightText: black,
    remove: cyan,
    reset: cyan,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  blueGrey: {
    primary: blueGrey,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: blueGrey,
    text: black,
    selectedBackground: blueGrey,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightBlueGrey,
    highlightText: black,
    remove: blueGrey,
    reset: blueGrey,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  deepPurple: {
    primary: deepPurple,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: deepPurple,
    text: black,
    selectedBackground: deepPurple,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: indigo,
    revealText: white,
    highlightBackground: lightDeepPurple,
    highlightText: black,
    remove: deepPurple,
    reset: deepPurple,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  green: {
    primary: green,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: green,
    text: black,
    selectedBackground: green,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightGreen,
    highlightText: black,
    remove: green,
    reset: green,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  indigo: {
    primary: indigo,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: indigo,
    text: black,
    selectedBackground: indigo,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightIndigo,
    highlightText: black,
    remove: indigo,
    reset: indigo,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  pink: {
    primary: pink,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: pink,
    text: black,
    selectedBackground: pink,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: indigo,
    revealOpacityBackground: indigo,
    revealText: white,
    highlightBackground: lightPink,
    highlightText: black,
    remove: pink,
    reset: pink,
    reveal: indigo,
    showHints: yellow,
    barStyle: 'light-content',
  },
  purple: {
    primary: purple,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: purple,
    text: black,
    selectedBackground: purple,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: indigo,
    revealText: white,
    highlightBackground: lightPurple,
    highlightText: black,
    remove: purple,
    reset: purple,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
  red: {
    primary: red,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: red,
    text: black,
    selectedBackground: red,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: indigo,
    revealOpacityBackground: indigo,
    revealText: white,
    highlightBackground: lightRed,
    highlightText: black,
    remove: red,
    reset: red,
    reveal: indigo,
    showHints: yellow,
    barStyle: 'light-content',
  },
  teal: {
    primary: teal,
    secondary: white,
    inactive: gray,
    margin: black,
    background: white,
    opacityBackground: teal,
    text: black,
    selectedBackground: teal,
    selectedOpacity: white,
    selectedText: white,
    revealBackground: red,
    revealOpacityBackground: red,
    revealText: white,
    highlightBackground: lightTeal,
    highlightText: black,
    remove: teal,
    reset: teal,
    reveal: red,
    showHints: yellow,
    barStyle: 'light-content',
  },
};

export { cellColorTheme };

export const margins = StyleSheet.create({
  cellNormBox: {
    marginTop: SUDOKU_CELL_NORMAL_MARGIN,
    marginBottom: SUDOKU_CELL_NORMAL_MARGIN,
    marginRight: SUDOKU_CELL_NORMAL_MARGIN,
    marginLeft: SUDOKU_CELL_NORMAL_MARGIN,
  },
  cellNormLeft: {
    marginLeft: SUDOKU_CELL_NORMAL_MARGIN,
  },
  cellNormTop: {
    marginTop: SUDOKU_CELL_NORMAL_MARGIN,
  },
  cellNormBottomRight: {
    marginBottom: SUDOKU_CELL_NORMAL_MARGIN,
    marginRight: SUDOKU_CELL_NORMAL_MARGIN,
  },
  // Start control cells margin for portrait
  cellNormTopBottomRight: {
    marginTop: SUDOKU_CELL_NORMAL_MARGIN,
    marginBottom: SUDOKU_CELL_NORMAL_MARGIN,
    marginRight: SUDOKU_CELL_NORMAL_MARGIN,
  },
  cellNormTopBottomSubRight: {
    marginTop: SUDOKU_CELL_NORMAL_MARGIN,
    marginBottom: SUDOKU_CELL_NORMAL_MARGIN,
    marginRight: SUDOKU_CELL_SUBGRID_MARGIN,
  },
  // End control cells margin for portrait
  // Start control cells margin for landscape
  cellNormLeftRightBottom: {
    marginLeft: SUDOKU_CELL_NORMAL_MARGIN,
    marginRight: SUDOKU_CELL_NORMAL_MARGIN,
    marginBottom: SUDOKU_CELL_NORMAL_MARGIN,
  },
  cellNormLeftRightSubBottom: {
    marginLeft: SUDOKU_CELL_NORMAL_MARGIN,
    marginRight: SUDOKU_CELL_NORMAL_MARGIN,
    marginBottom: SUDOKU_CELL_SUBGRID_MARGIN,
  },
  // End control cells margin for landscape
  cellSubRight: {
    marginRight: SUDOKU_CELL_SUBGRID_MARGIN,
  },
  cellSubRightNormBottom: {
    marginRight: SUDOKU_CELL_SUBGRID_MARGIN,
    marginBottom: SUDOKU_CELL_NORMAL_MARGIN,
  },
  cellSubBottom: {
    marginBottom: SUDOKU_CELL_SUBGRID_MARGIN,
  },
  cellSubBottomNormRight: {
    marginRight: SUDOKU_CELL_NORMAL_MARGIN,
    marginBottom: SUDOKU_CELL_SUBGRID_MARGIN,
  },
  cellSubBottomRight: {
    marginRight: SUDOKU_CELL_SUBGRID_MARGIN,
    marginBottom: SUDOKU_CELL_SUBGRID_MARGIN,
  },
  // Flatlist
  flatListItem: {
    alignSelf: 'center',
    marginBottom: FLAT_LIST_MARGIN_SIZE,
  },
  flatListFirstItem: {
    alignSelf: 'center',
    marginTop: FLAT_LIST_MARGIN_SIZE,
    marginBottom: FLAT_LIST_MARGIN_SIZE,
  },
});

export function createCellStylesLandscape(themeName: string) {
  const styles = StyleSheet.create({
    cellRows: {
      flexDirection: 'row',
      backgroundColor: cellColorTheme[themeName].margin,
    },
    sudokuContainer: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    sudokuContainerForInfo: {
      marginLeft: GAP_BETWEEN_COMPONENTS,
    },
    sudokuContainerForBoard: {
      marginLeft: GAP_BETWEEN_COMPONENTS,
      marginRight: GAP_BETWEEN_COMPONENTS,
    },
    sudokuContainerForController: {
      marginRight: GAP_BETWEEN_COMPONENTS,
    },
    board: {
      paddingTop: SUDOKU_CELL_NORMAL_MARGIN,
      paddingLeft: SUDOKU_CELL_NORMAL_MARGIN,
      backgroundColor: cellColorTheme[themeName].margin,
    },
    controllContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    controlCellsContainer: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: cellColorTheme[themeName].margin,
    },
    controlCellsContainerHide: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: cellColorTheme[themeName].margin,
      opacity: 0,
    },
    controlBtnContainer: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    controlBtnContainerHide: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      opacity: 0,
    },
    // Flatlist
    flatListItemSelected: {
      alignSelf: 'center',
      marginBottom: FLAT_LIST_MARGIN_SIZE,
      backgroundColor: cellColorTheme[themeName].primary,
      opacity: 0.3,
    },
    flatListFirstItemSelected: {
      alignSelf: 'center',
      marginTop: FLAT_LIST_MARGIN_SIZE,
      marginBottom: FLAT_LIST_MARGIN_SIZE,
      opacity: 0.3,
    },
  });

  return { ...margins, ...styles };
}

export function createCellStylesPortrait(themeName: string) {
  const styles = StyleSheet.create({
    cellRows: {
      flexDirection: 'row',
      backgroundColor: cellColorTheme[themeName].margin,
    },
    sudokuContainer: {
      flex: 1,
      flexDirection: 'column',
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    sudokuContainerForInfo: {
      marginTop: GAP_BETWEEN_COMPONENTS,
    },
    sudokuContainerForBoard: {
      marginTop: GAP_BETWEEN_COMPONENTS,
      marginBottom: GAP_BETWEEN_COMPONENTS,
    },
    sudokuContainerForController: {
      marginBottom: GAP_BETWEEN_COMPONENTS,
    },
    board: {
      paddingTop: SUDOKU_CELL_NORMAL_MARGIN,
      paddingLeft: SUDOKU_CELL_NORMAL_MARGIN,
      backgroundColor: cellColorTheme[themeName].margin,
    },
    controllContainer: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    controlCellsContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: cellColorTheme[themeName].margin,
    },
    controlCellsContainerHide: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: cellColorTheme[themeName].margin,
      opacity: 0,
    },
    controlBtnContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    controlBtnContainerHide: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      opacity: 0,
    },
    // Flatlist
    flatListItemSelected: {
      alignSelf: 'center',
      marginBottom: FLAT_LIST_MARGIN_SIZE,
      backgroundColor: cellColorTheme[themeName].primary,
      opacity: 0.3,
    },
    flatListFirstItemSelected: {
      alignSelf: 'center',
      marginTop: FLAT_LIST_MARGIN_SIZE,
      marginBottom: FLAT_LIST_MARGIN_SIZE,
      opacity: 0.3,
    },
  });

  return { ...margins, ...styles };
}
